# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-04-15 17:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yunwei', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='XLS',
        ),
        migrations.AlterModelTable(
            name='profile',
            table=None,
        ),
    ]
