# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-24 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yunwei', '0003_auto_20170523_0610'),
    ]

    operations = [
        migrations.CreateModel(
            name='BLOG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nowtime', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=1000)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MESSAGE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nowtime', models.DateTimeField(auto_now_add=True)),
                ('blogid', models.BigIntegerField()),
                ('username', models.CharField(max_length=50)),
                ('content', models.TextField()),
            ],
        ),
    ]
